name: placeit
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.1
  firebase_core: ^3.12.1
  google_fonts: ^6.1.0
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  file_picker: ^9.1.0
  device_info_plus: ^11.3.3
  permission_handler: ^11.4.0
  firebase_app_check: ^0.3.2+4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/chair.glb
    - assets/logo.png
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/success.gif


